import type { AlertParts, AlertPopupParts, BadgeParts, ButtonGroupParts, ButtonParts, CheckboxParts, CollapsableCheckboxParts, CollapsablePanelParts, CollapsableRadioParts, CollapsableToggleParts, CollapseParts, DrawerParts, DropdownButtonParts, DropdownItemParts, DropdownMenuParts, FloatingPanelParts, IconParts, NavLinkParts, NavMenuParts, PopperParts, RadioParts, SelectParts, SwitchParts, TabParts, TabsParts, TooltipParts } from 'jimu-ui';
export interface ComponentNameToPartKey {
    [key: string]: string;
    CssBaseline: 'root';
    Header: 'root';
    Footer: 'root';
    Alert: AlertParts;
    AlertPopup: AlertPopupParts;
    Badge: BadgeParts;
    Button: ButtonParts;
    ButtonGroup: ButtonGroupParts;
    Checkbox: CheckboxParts;
    Collapse: CollapseParts;
    CollapsablePanel: CollapsablePanelParts;
    CollapsableCheckbox: CollapsableCheckboxParts;
    CollapsableRadio: CollapsableRadioParts;
    CollapsableToggle: CollapsableToggleParts;
    Drawer: DrawerParts;
    Dropdown: 'root';
    DropdownMenu: DropdownMenuParts;
    DropdownItem: DropdownItemParts;
    DropdownButton: DropdownButtonParts;
    FloatingPanel: FloatingPanelParts;
    Icon: IconParts;
    Link: 'root';
    Nav: 'root';
    Navbar: 'root';
    NavItem: 'root';
    NavMenu: NavMenuParts;
    NavLink: NavLinkParts;
    Option: 'root';
    Paper: 'root';
    Popper: PopperParts;
    Radio: RadioParts;
    Select: SelectParts;
    Slider: 'root';
    Surface: 'root';
    SVG: 'root';
    Switch: SwitchParts;
    Tab: TabParts;
    Tabs: TabsParts;
    Tooltip: TooltipParts;
}
