const indexes = [
  {
    id: 1,
    label: "Μέση θερμοκρασία (°C) - TG",
    labelEn: "Mean temperature (°C) - TG",
    value: "tmean",
    has_seasonal_data: true,
    unit: "°C",
    unitEn: "°C",
    index: "TG",
    precision: 3,
  },
  {
    id: 2,
    label: "Μέση ελάχιστη θερμοκρασία (°C) - TN",
    labelEn: "Mean minimum temperature (°C) - TN",
    value: "tmin",
    unit: "°C",
    unitEn: "°C",
    index: "TN",
    precision: 3,
  },
  {
    id: 3,
    label: "Μέση μέγιστη θερμοκρασία (°C) - TX",
    labelEn: "Mean maximum temperature (°C) - TX",
    value: "tmax",
    unit: "°C",
    unitEn: "°C",
    index: "TX",
    precision: 3,
  },
  {
    id: 4,
    label: "Αριθμός ημερών με TX > 30°C - θερμές ημέρες",
    labelEn: "Number of days with TX > 30°C - hot days",
    value: "hot30",
    unit: "ημέρες",
    unitEn: "days",
    index: "TX > 30°C",
    precision: 1,
  },
  {
    id: 5,
    label: "Αριθμός ημερών με TX > 35°C - πολύ θερμές ημέρες",
    labelEn: "Number of days with TX > 35°C - very hot days",
    value: "hot35",
    unit: "ημέρες",
    unitEn: "days",
    index: "TX > 35°C",
    precision: 1,
  },
  {
    id: 6,
    label: "Αριθμός ημερών με TN > 20°C - τροπικές νύχτες",
    labelEn: "Number of days with TN > 20°C - tropical nights",
    value: "tr20",
    unit: "ημέρες",
    unitEn: "days",
    index: "TN > 20°C",
    precision: 1,
  },
  {
    id: 7,
    label: "Αριθμός ημερών με TN < 0°C - νυχτερινός παγετός",
    labelEn: "Number of days with TN < 0°C - nighttime frost",
    value: "FN",
    unit: "ημέρες",
    unitEn: "days",
    index: "TN < 0°C",
    precision: 1,
  },
  {
    id: 8,
    label:
      "Αριθμός ημερών με ισχυρές ανάγκες για θέρμανση (ημέρες με TG < 10°C)",
    labelEn: "Number of days with strong heating needs (days with TG < 10°C)",
    value: "HeatingDD",
    unit: "ημέρες",
    unitEn: "days",
    index: "TG  <10 °C",
    precision: 1,
  },
  {
    id: 9,
    label: "Αριθμός ημερών με ισχυρές ανάγκες για ψύξη (ημέρες με TG > 30°C)",
    labelEn: "Number of days with strong cooling needs (days with TG > 30°C)",
    value: "CoolingDD",
    unit: "ημέρες",
    unitEn: "days",
    index: "TG > 30 °C",
    precision: 1,
  },
  {
    id: 10,
    label: "Ολική βροχόπτωση (mm) - PR",
    labelEn: "Total precipitation (mm) - PR",
    value: "PR_GR_3racmo",
    has_seasonal_data: true,
    unit: "mm",
    unitEn: "mm",
    index: "PR",
    precision: 3,
  },
  {
    id: 11,
    label:
      "Μέγιστη διάρκεια διαδοχικών ημερών με PR < 1mm - μέγιστη διάρκεια ξηρασίας σε ημέρες",
    labelEn:
      "Maximum number of consecutive days with PR < 1mm – maximum dry spell duration (in days)",
    value: "dryspel",
    unit: "ημέρες",
    unitEn: "days",
    index: "PR < 1mm",
    precision: 1,
  },
  {
    id: 12,
    label: "Αριθμός ημερών με PR > 10mm - ημέρες ισχυρής βροχόπτωσης",
    labelEn: "Number of days with PR > 10mm - days with heavy rainfall",
    value: "pr10_3racmo",
    unit: "ημέρες",
    unitEn: "days",
    index: "PR > 10mm",
    precision: 1,
  },
  {
    id: 13,
    label: "Αριθμός ημερών PR > 20mm - ημέρες πολύ ισχυρής βροχόπτωσης",
    labelEn: "Number of days with PR > 20mm - days with very heavy rainfall",
    value: "pr20_3racmo",
    unit: "ημέρες",
    unitEn: "days",
    index: "PR > 20mm",
    precision: 1,
  },
  {
    id: 14,
    label: "Αριθμός ημερών με PR > 1mm - ημέρες βροχόπτωσης",
    labelEn: "Number of days with PR > 1mm - days with rainfall",
    value: "wetdays",
    unit: "ημέρες",
    unitEn: "days",
    index: "PR > 1mm",
    precision: 1,
  },
  {
    id: 15,
    label: "Αριθμός ημερών με PR < 1mm - ημέρες χωρίς βροχόπτωση",
    labelEn: "Number of days with PR < 1mm - days without rainfall",
    value: "drydays",
    unit: "ημέρες",
    unitEn: "days",
    index: "PR < 1mm",
    precision: 1,
  },
  {
    id: 16,
    label: "Μέση σχετική υγρασία - RH (%)",
    labelEn: "Mean relative humidity - RH (%)",
    value: "RH",
    unit: "%",
    unitEn: "%",
    index: "RH",
    precision: 3,
  },
  {
    id: 17,
    label: "Μέση ταχύτητα ανέμου (m/s)",
    labelEn: "Mean wind velocity (m/s)",
    value: "wind",
    has_seasonal_data: true,
    unit: "m/sec",
    unitEn: "m/s",
    index: "Wind",
    precision: 3,
  },
  {
    id: 18,
    label: "Αριθμός ημερών με δείκτη δυσφορίας (Humidex) > 38°C",
    labelEn: "Number of days with discomfort index (Humidex) > 38°C",
    value: "Humidex38",
    unit: "ημέρες",
    unitEn: "days",
    index: "(Humidex) >38 ºC",
    precision: 1,
  },
  {
    id: 19,
    label: "Αριθμός ημερών με δείκτη δυσφορίας (Humidex) > 40°C",
    labelEn: "Number of days with discomfort index (Humidex) > 40°C",
    value: "Humidex40",
    unit: "ημέρες",
    unitEn: "days",
    index: "(Humidex) >40 ºC",
    precision: 1,
  },
  {
    id: 20,
    label: "Αριθμός ημερών με δείκτη δυσφορίας (humidex) > 46°C",
    labelEn: "Number of days with discomfort index (Humidex) > 46°C",
    value: "Humidex46",
    unit: "ημέρες",
    unitEn: "days",
    index: "(Humidex) >46 ºC",
    precision: 1,
  },
  {
    id: 21,
    label:
      "Μέσος δείκτης κινδύνου δασικής πυρκαγιάς -FWI αντιπυρικής περιόδου (Μάιος- Οκτώβριος)",
    labelEn:
      "Mean Forest Fire Weather Index (FWI) during the fire season (May–October)",
    value: "fwi_fireseason",
    unit: "",
    unitEn: "",
    index: "FWI",
    precision: 3,
  },
  {
    id: 22,
    label:
      "Αριθμός ημερών με ακραίο κίνδυνο εκδήλωσης δασικής πυρκαγιάς (FWI > 50)",
    labelEn: "Number of days with extreme forest fire risk (FWI > 50)",
    value: "fwi50",
    unit: "ημέρες",
    unitEn: "days",
    index: "FWI > 50",
    precision: 1,
  },
  {
    id: 23,
    label:
      "Μέση ετήσια εισερχόμενη μικρού μήκους κύματος ακτινοβολία (Watt/m²)",
    labelEn: "Mean annual received short wave radiation (Watt/m²)",
    value: "Rsdss_YEAR",
    unit: "m2",
    unitEn: "m²",
    index: "Watt",
    precision: 3,
  },
  {
    id: 24,
    label: "Μέσo ετήσιo κλάσμα νεφοκάλυψης (%)",
    labelEn: "Mean annual percentage of cloud cover (%)",
    value: "Cl_Cov_YEAR",
    unit: "% - έτος",
    unitEn: "% - year",
    index: "CL COV",
    precision: 3,
  },
];

export default indexes;
